# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test unit

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  install:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: yarn --frozen-lockfile

  build:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: yarn run build
        env:
          NODE_ENV: production

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Unit test
        run: yarn run test
        env:
          NODE_ENV: production

  lint:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - name: Lint
        run: yarn run lint
        env:
          NODE_ENV: production
 
  deploy:
    needs: [build,test,lint]
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/scp-action@master
      - name: Deploy
        env:
          HOST: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.SSHKEY }}
        with:
          source: "."
          target: "/usr/local/lsws/davcs86me/html/node"
  
